version: '2'
services:
  geteway-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/geteway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=geteway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
